package com.hcl.core;
// Generated Mar 3, 2019 11:59:25 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * EmpTbl generated by hbm2java
 */
@Entity
@Table(name = "EMP_TBL", schema = "BRAINWAVE")
public class Employee implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int empid;
	private String empname;
	private Integer salary;

	public Employee() {
	}

	public Employee(int empid) {
		this.empid = empid;
	}

	public Employee(int empid, String empname, Integer salary) {
		this.empid = empid;
		this.empname = empname;
		this.salary = salary;
	}

	@Id

	@Column(name = "EMPID", unique = true, nullable = false, precision = 5, scale = 0)
	public int getEmpid() {
		return this.empid;
	}

	public void setEmpid(int empid) {
		this.empid = empid;
	}

	@Column(name = "EMPNAME", length = 10)
	public String getEmpname() {
		return this.empname;
	}

	public void setEmpname(String empname) {
		this.empname = empname;
	}

	@Column(name = "SALARY", precision = 7, scale = 0)
	public Integer getSalary() {
		return this.salary;
	}

	public void setSalary(Integer salary) {
		this.salary = salary;
	}

}
