package com.hcl.core;
// Generated 21 May, 2019 7:21:35 PM by Hibernate Tools 5.2.11.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * EmpTbl generated by hbm2java
 */
@Entity
@Table(name = "EMP_TBL", schema = "BRAINWAVE")
public class EmpTbl implements java.io.Serializable {

	private BigDecimal eno;
	private String name;
	private BigDecimal salary;

	public EmpTbl() {
	}

	public EmpTbl(BigDecimal eno) {
		this.eno = eno;
	}

	public EmpTbl(BigDecimal eno, String name, BigDecimal salary) {
		this.eno = eno;
		this.name = name;
		this.salary = salary;
	}

	@Id

	@Column(name = "ENO", unique = true, nullable = false, scale = 0)
	public BigDecimal getEno() {
		return this.eno;
	}

	public void setEno(BigDecimal eno) {
		this.eno = eno;
	}

	@Column(name = "NAME")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "SALARY", precision = 38, scale = 0)
	public BigDecimal getSalary() {
		return this.salary;
	}

	public void setSalary(BigDecimal salary) {
		this.salary = salary;
	}

}
